package com.dsharnessmobile.shell

import android.content.Context
import android.media.MediaScannerConnection
import android.os.Environment
import android.util.Log
import java.io.File
import java.nio.file.Files
import org.apache.commons.compress.archivers.tar.TarArchiveEntry
import org.apache.commons.compress.archivers.tar.TarArchiveInputStream
import org.apache.commons.compress.compressors.xz.XZCompressorInputStream

/**
 * Owns the embedded Termux environment snapshot: first-launch extraction into
 * filesDir/usr and the dsh engine process lifecycle (PATH/LD_LIBRARY_PATH/HOME
 * injected explicitly — the snapshot is self-sufficient, no Termux app needed).
 */
class EngineManager(private val context: Context, private val pickToken: String? = null) {

  val usrDir = File(context.filesDir, "usr")
  val homeDir = File(context.filesDir, "home")

  /**
   * Public export repo: /storage/emulated/0/Documents/dshdata.
   * Holds only user-initiated session zip exports (exports/) plus a .nomedia anti-scan marker;
   * all runtime user data lives back in private app data (files/home/.dsh).
   */
  val dshDataDir: File
    get() {
      val publicDocs = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOCUMENTS)
        ?: File(context.filesDir, "dshdata-fallback")
      return File(publicDocs, "dshdata")
    }
  private val nodeBin = File(usrDir, "bin/node")
  private val dshBin = File(usrDir, "lib/node_modules/@deepseek-ai/dsh/lib/bin.js")
  private var engineProcess: Process? = null

  val engineReady: Boolean get() = nodeBin.exists()

  /** Embedded snapshot fingerprint (assets/snapshot.sha256, generated by build-release.ps1). */
  private fun bundledFingerprint(): String = try {
    context.assets.open("snapshot.sha256").bufferedReader().use { it.readText().trim() }
  } catch (_: Exception) {
    ""
  }

  private fun fingerprintFile(): File = File(context.filesDir, ".snapshot-fingerprint")

  /**
   * Whether the snapshot is extracted and matches the embedded version: node exists + fingerprint match.
   * Upgrade lesson (v0.10.5→v0.10.6): engineReady only checked node existence, so an upgrade never
   * re-extracted → old plugins kept running (injection-guard fixes etc. never took effect).
   */
  fun snapshotFresh(): Boolean {
    if (!nodeBin.exists()) return false
    val fp = bundledFingerprint()
    if (fp.isEmpty()) return true // no fingerprint file (legacy build): don't force a re-extract
    return fingerprintFile().exists() && fingerprintFile().readText().trim() == fp
  }

  /**
   * Upgrade/snapshot change: back up user data → fully re-extract the embedded snapshot → restore user
   * data → write the fingerprint. The snapshot strips sessions/storages/attachments/credentials/settings
   * (see make-snapshot.sh), so a plain re-extract would "lose" that private data — backup first, restore
   * after; factory profiles (cordis*.yml/node_modules) follow the snapshot (manual patches must be
   * re-applied on top of the new baseline). On any failure: restore the backup and keep the old runtime
   * (retried on next start).
   */
  fun refreshSnapshot(onProgress: (Long, Long) -> Unit): Boolean {
    val backup = File(context.filesDir, ".dsh-backup")
    val dsh = File(homeDir, ".dsh")
    try {
      if (dsh.exists()) {
        backup.deleteRecursively()
        // Upgrade-residue tolerance (v0.12.4): profile node_modules may carry dangling symlinks
        // pointing at packages that no longer exist (npm layout changes) — copyRecursively's
        // exists() check on a dangling link throws NoSuchFileException and fails the whole refresh.
        // Drop broken links before backing up (profiles follow the snapshot; the backup omits them).
        dsh.walkTopDown().forEach { if (java.nio.file.Files.isSymbolicLink(it.toPath()) && !it.exists()) it.delete() }
        dsh.copyRecursively(backup)
      }
      val ok = extractSnapshot(onProgress)
      if (!ok) {
        restoreUserData(backup, dsh)
        Log.e(TAG, "snapshot refresh: extract failed, kept old runtime")
        return false
      }
      restoreUserData(backup, dsh)
      backup.deleteRecursively()
      fingerprintFile().writeText(bundledFingerprint())
      Log.i(TAG, "snapshot refreshed (fingerprint " + bundledFingerprint().take(12) + ")")
      return true
    } catch (t: Throwable) {
      restoreUserData(backup, dsh)
      Log.e(TAG, "snapshot refresh failed; kept old runtime", t)
      return false
    }
  }

  /** Restore the snapshot-stripped user data dirs/files (copied back from the backup into private .dsh).
   *  Never throws (Review 2026-08-18 R2): refreshSnapshot's failure branch calls this on a background
   *  thread, so a restore failure must not escape — otherwise the exception kills the thread and the UI
   *  hangs on "Updating runtime…" with no message. Failures only log; the backup is kept for a retry. */
  private fun restoreUserData(backup: File, dsh: File) {
    if (!backup.exists()) return
    for (name in listOf(
      "sessions", "storages", "attachments",
      ".credentials.yaml", "settings.yaml", ".anonymous-user-id", ".private-layout",
    )) {
      try {
        val src = File(backup, name)
        if (!src.exists()) continue
        val dst = File(dsh, name)
        if (dst.exists()) dst.deleteRecursively()
        src.copyRecursively(dst)
      } catch (t: Throwable) {
        Log.e(TAG, "restore user data failed for $name; backup kept at " + backup.absolutePath, t)
      }
    }
  }

  /** Process-level start guard (MainActivity and EngineService each construct their own EngineManager;
   *  instance fields are invisible across them — the double-start race needs companion-level CAS). */
  private val starting: Boolean
    get() = STARTING.get()

  /**
   * Extract the bundled snapshot archive into filesDir. Runs on any thread;
   * callers own the progress UI.
   * @param onProgress bytesDone, bytesTotal.
   * @returns true on success.
   */
  fun extractSnapshot(onProgress: (Long, Long) -> Unit): Boolean {
    return try {
      val fd = context.assets.openFd("snapshot.tar.xz")
      SnapshotExtractor.extract(context.assets.open("snapshot.tar.xz"), fd.length, usrDir.parentFile, onProgress)
      homeDir.mkdirs()
      true
    } catch (t: Throwable) {
      Log.e(TAG, "snapshot extract failed", t)
      false
    }
  }

  /**
   * Ensure the private DSH_HOME data layout is ready (idempotent, called from a background thread).
   *
   * Since v0.10.5 all runtime data lives in private app data; Documents/dshdata stays only as the
   * user-initiated export repo (exports/ + .nomedia). This method:
   *  - on a first/clean install: sets up the private .dsh layout and the public export repo;
   *  - when it detects a pre-v0.10.4 public migration layout (.migrated-from or private symlinks):
   *    performs a reverse migration, copying sessions/storages/attachments/profiles/settings.yaml
   *    back into private storage and cleaning up the public leftovers;
   *  - on any failure keeps the public data; the engine still starts with a private DSH_HOME and
   *    retries next time.
   *
   * DSH_HOME always stays in the private domain: the profiles/node_modules flat-fallback symlink
   * mechanism depends on the app-private domain (public FUSE forbids symlinks), so DSH_HOME must
   * never be migrated wholesale.
   */
  fun ensurePrivateDshData(): File {
    val dshData = dshDataDir
    val privateDsh = File(homeDir, ".dsh")
    privateDsh.mkdirs()
    val privateMarker = File(privateDsh, ".private-layout")
    if (privateMarker.exists()) {
      ensurePublicExportRepo(dshData)
      return privateDsh
    }
    if (isLegacyPublicLayout(dshData, privateDsh)) {
      try {
        reverseMigrate(dshData, privateDsh)
        privateMarker.writeText("private")
        ensurePublicExportRepo(dshData)
        Log.i(TAG, "dshdata reverse migration done -> " + privateDsh.absolutePath)
      } catch (t: Throwable) {
        // A migration failure must not block startup: DSH_HOME stays private, the engine works, retry later.
        Log.e(TAG, "dshdata reverse migration failed; keeping public data", t)
      }
    } else {
      // Clean install or already-private layout: just mark it, no migration needed.
      try {
        privateMarker.writeText("private")
      } catch (t: Throwable) {
        Log.w(TAG, "private layout marker write failed", t)
      }
      ensurePublicExportRepo(dshData)
    }
    return privateDsh
  }

  /** Detect the pre-v0.10.4 public migration layout. */
  private fun isLegacyPublicLayout(dshData: File, privateDsh: File): Boolean {
    if (File(dshData, ".migrated-from").exists()) return true
    for (name in listOf("sessions", "storages", "attachments")) {
      if (isSymlink(File(privateDsh, name))) return true
    }
    for (profile in listOf("web", "headless")) {
      for (name in listOf("cordis.yml", "cordis.patch.yml")) {
        if (isSymlink(File(privateDsh, "profiles/$profile/$name"))) return true
      }
    }
    return false
  }

  /** Reverse migration: copy public data back into private storage, clean up the public leftovers. */
  private fun reverseMigrate(dshData: File, privateDsh: File) {
    for (name in listOf("sessions", "storages", "attachments")) {
      reverseMigrateDir(File(privateDsh, name), File(dshData, name))
    }
    for (profile in listOf("web", "headless")) {
      for (name in listOf("cordis.yml", "cordis.patch.yml")) {
        reverseMigrateFile(
          File(privateDsh, "profiles/$profile/$name"),
          File(dshData, "profiles/$profile/$name"),
        )
      }
    }
    reverseMigrateFile(File(privateDsh, "settings.yaml"), File(dshData, "settings.yaml"))

    // Clean up stale public data (conflicts were renamed *.public-backup, so they're untouched).
    val removedPaths = mutableListOf<String>()
    for (name in listOf("sessions", "storages", "attachments", "profiles", "settings.yaml", ".migrated-from")) {
      val f = File(dshData, name)
      if (f.exists()) {
        removedPaths += f.absolutePath
        if (!f.deleteRecursively()) {
          throw java.io.IOException("failed to delete public path " + f.absolutePath)
        }
      }
    }
    // Tell MediaScanner the old public subdirs are gone, clearing the fake video entries it indexed.
    if (removedPaths.isNotEmpty()) {
      try {
        MediaScannerConnection.scanFile(context, removedPaths.toTypedArray(), null, null)
      } catch (t: Throwable) {
        Log.w(TAG, "media scan cleanup failed", t)
      }
    }
  }

  /** Dir-level reverse migration: drop the private symlink, copy the public entity back with a verified copy, then delete the public source. */
  private fun reverseMigrateDir(privateDir: File, publicDir: File) {
    if (isSymlink(privateDir)) {
      Files.delete(privateDir.toPath())
    }
    if (!publicDir.isDirectory) return
    if (privateDir.isDirectory) {
      if (privateDir.listFiles()?.isNotEmpty() == true) {
        // Conflict: the private entity wins; the public copy is kept aside for review.
        val backup = uniqueBackup(publicDir)
        if (!publicDir.renameTo(backup)) {
          throw java.io.IOException("failed to backup public dir " + publicDir.absolutePath)
        }
        Log.w(TAG, "private " + privateDir.absolutePath + " exists; public kept as " + backup.absolutePath)
        return
      }
      privateDir.deleteRecursively()
    }
    privateDir.parentFile?.mkdirs()
    copyTreeVerified(publicDir, privateDir)
    if (!publicDir.deleteRecursively()) {
      throw java.io.IOException("failed to delete public source " + publicDir.absolutePath)
    }
  }

  /** File-level reverse migration: drop the private symlink, copy the public file back, then delete the public source. */
  private fun reverseMigrateFile(privateFile: File, publicFile: File) {
    if (isSymlink(privateFile)) {
      Files.delete(privateFile.toPath())
    }
    if (!publicFile.isFile) return
    if (privateFile.exists()) {
      if (privateFile.length() > 0) {
        // The public file is the post-migration active copy (settings/profiles); the public one wins,
        // and the stale private entity is kept as a backup rather than silently deleted.
        val backup = uniquePrivateBackup(privateFile)
        if (!privateFile.renameTo(backup)) {
          throw java.io.IOException("failed to backup private file " + privateFile.absolutePath)
        }
        Log.w(TAG, "private file backed up as " + backup.absolutePath)
      } else {
        privateFile.delete()
      }
    }
    privateFile.parentFile?.mkdirs()
    publicFile.copyTo(privateFile, overwrite = true)
    if (privateFile.length() != publicFile.length()) {
      throw java.io.IOException("copy verification failed for " + publicFile.absolutePath)
    }
    if (!publicFile.delete()) {
      throw java.io.IOException("failed to delete public source " + publicFile.absolutePath)
    }
  }

  /** Ensure the public export repo exists: root dir + .nomedia + exports/. */
  private fun ensurePublicExportRepo(dshData: File) {
    try {
      dshData.mkdirs()
      File(dshData, ".nomedia").writeText("")
      File(dshData, "exports").mkdirs()
    } catch (t: Throwable) {
      Log.w(TAG, "public export repo setup failed", t)
    }
  }

  private fun isSymlink(file: File): Boolean = Files.isSymbolicLink(file.toPath())

  private fun uniqueBackup(publicFile: File): File {
    var candidate = File(publicFile.parentFile, publicFile.name + ".public-backup")
    var i = 1
    while (candidate.exists()) {
      candidate = File(publicFile.parentFile, publicFile.name + ".public-backup-" + i)
      i++
    }
    return candidate
  }

  private fun uniquePrivateBackup(privateFile: File): File {
    var candidate = File(privateFile.parentFile, privateFile.name + ".private-backup")
    var i = 1
    while (candidate.exists()) {
      candidate = File(privateFile.parentFile, privateFile.name + ".private-backup-" + i)
      i++
    }
    return candidate
  }

  /** Recursively copy a directory tree, verifying the file count and total size. */
  private fun copyTreeVerified(src: File, dst: File) {
    dst.mkdirs()
    src.listFiles()?.forEach { f ->
      val target = File(dst, f.name)
      if (f.isDirectory) {
        copyTreeVerified(f, target)
      } else {
        f.copyTo(target, overwrite = true)
      }
    }
    val srcFiles = src.walkBottomUp().filter { it.isFile }.toList()
    val dstFiles = dst.walkBottomUp().filter { it.isFile }.toList()
    val srcSize = srcFiles.sumOf { it.length() }
    val dstSize = dstFiles.sumOf { it.length() }
    if (srcFiles.size != dstFiles.size || srcSize != dstSize) {
      throw java.io.IOException("copy verification failed for " + src.absolutePath)
    }
  }

  /**
   * Runtime patches: overlay fix files from assets/patched onto the corresponding snapshot
   * locations (idempotent). Overlayed fixes (all marked by a sentinel string in the target file,
   * so they are re-applied automatically after a snapshot refresh/re-extract):
   *  - primitives-index.js: clipboard fallback for WebViews where navigator.clipboard is denied
   *  - attachment-local-index.js: Android link(2) blocked by sepolicy → copyFile fallback + EACCES tolerance
   *  - web-frontend-index.html: immersive viewport-fit=cover patch
   *  - llm-deepseek-index.js: DeepSeek-V4-Flash-Vision-Exp catalog entry (multimodal vision model,
   *    official since dsh 0.1.1-rc.1). Stores the rc.1 adapter as a full-file overlay, so the model
   *    is selectable on any base snapshot; skip-marker is the model id itself, so a base whose
   *    bundled adapter already ships the model (0.1.1-rc.1+) leaves the native file untouched.
   *  - session-persistence-jsonl-index.js / fs-local-index.js: Android link(2) fallback — dsh
   *    0.1.1-rc.1 dropped the EACCES/EPERM/ENOTSUP → rename fallback that rc.8 shipped; Android
   *    app domains forbid link(2) (sepolicy), re-add it as a full-file overlay (as in rc.8).
   *    Note: these are full-file overlays pinned to the rc.1 bundle; when the snapshot is next
   *    upgraded, re-evaluate whether the overlay is still needed (upstream may re-add the
   *    fallback) instead of blindly overwriting the newer native file.
   * (v0.12.4 rc8 removed the onImagePicked/llm-deepseek/textzoom patches — rc8's native image
   * request support and no-cache hardening supersede them; the vision-exp patch re-adds a
   * catalog-only llm-deepseek overlay for the model released 2026-08-21.)
   */
  private fun applyRuntimePatches() {
    val dshPkgs = File(usrDir, "lib/node_modules/@deepseek-ai/dsh/node_modules/@deepseek-ai")
    val webDist = File(dshPkgs, "dsh-web-frontend/dist")
    val home = File(homeDir, ".dsh")
    // v0.12.4 (rc8) migration: onImagePicked/describeImage/bundle-hardening/textzoom patches
    // were removed — rc8's official native image request (serializeRequestWithImages) and no-cache
    // hardening cover them; the textzoom feature was dropped after the settings-general rework
    // (the bridge method is kept).
    applyAssetPatch("patched/primitives-index.js",
      File(dshPkgs, "dsh-client-ui-primitives/lib/index.js"), "dsh-mobile-clip-fallback")
    applyAssetPatch("patched/attachment-local-index.js",
      File(dshPkgs, "dsh-attachment-local/lib/index.js"), "attachment-ancestor-sync-eacces-tolerance")
    applyAssetPatch("patched/web-frontend-index.html",
      File(webDist, "index.html"), "viewport-fit=cover")
    applyAssetPatch("patched/llm-deepseek-index.js",
      File(dshPkgs, "dsh-llm-deepseek/lib/index.js"), "deepseek-v4-flash-vision-exp")
    applyAssetPatch("patched/session-persistence-jsonl-index.js",
      File(dshPkgs, "dsh-session-persistence-jsonl/lib/index.js"), "jsonl-link-eacces-fallback")
    applyAssetPatch("patched/fs-local-index.js",
      File(dshPkgs, "dsh-fs-local/lib/index.js"), "fs-link-eacces-fallback")
  }

  /** Overwrite-style patch: skipped when the target already contains the marker string. */
  private fun applyAssetPatch(asset: String, target: File, marker: String) {
    // Patches track bundle layouts: when the runtime no longer ships the patched package
    // (e.g. dsh-client-ui-primitives dropped from the dependency graph in dsh 0.1.1-rc.1),
    // stop applying instead of littering a dead overlay into to the tree.
    if (!target.parentFile.exists()) {
      Log.i(TAG, "runtime patch skipped (target package absent): $asset")
      return
    }
    if (target.exists() && target.readText().contains(marker)) return
    try {
      context.assets.open(asset).use { input ->
        target.parentFile?.mkdirs()
        target.outputStream().use { out -> input.copyTo(out) }
      }
      Log.i(TAG, "runtime patch applied: $asset -> $target")
    } catch (e: Exception) {
      Log.e(TAG, "runtime patch failed: $asset", e)
    }
  }

  /** Append-style patch (for cordis.patch.yml, keeping the user's existing entries). */
  private fun applyAssetPatchAppend(asset: String, target: File, marker: String) {
    if (target.exists() && target.readText().contains(marker)) return
    try {
      val content = context.assets.open(asset).bufferedReader().use { it.readText() }
      target.parentFile?.mkdirs()
      val existing = if (target.exists()) target.readText() else ""
      val sep = if (existing.isNotBlank() && !existing.endsWith("\n")) "\n" else ""
      target.writeText(existing + sep + content)
      Log.i(TAG, "runtime patch appended: $asset -> $target")
    } catch (e: Exception) {
      Log.e(TAG, "runtime patch failed: $asset", e)
    }
  }

  /** Start the dsh web engine from the embedded snapshot. */
  fun startEngine(port: Int = 3080): Boolean {
    // LD_PRELOAD depends on the snapshot's termux-exec lib: when missing, every child exec fails,
    // and combined with the cooldown window that means a silent 90s engine outage — assert explicitly
    // before starting and fail loudly if absent.
    val preload = File(usrDir, "lib/libtermux-exec-ld-preload.so")
    if (!preload.exists()) {
      Log.e(TAG, "engine start failed: termux-exec preload missing at " + preload.absolutePath)
      return false
    }
    val now = System.currentTimeMillis()
    // Process-level CAS: only one concurrent call really starts (device-measured EADDRINUSE double-start).
    if (!STARTING.compareAndSet(false, true)) return true
    // Cooldown window: no re-start within 90s of the last attempt (a cold boot takes 20-45s).
    // Review 2026-08-18 (L2 semantics): returning true here means "no further start needed"
    // (the engine is most likely already starting), not "this call started it successfully" — callers
    // poll engine reachability themselves, so this never causes a wrong wait, but it must not be
    // read as proof of success.
    if (now - EngineManager.lastStartAttemptAt < START_COOLDOWN_MS) {
      STARTING.set(false)
      LogCollector.log(TAG, "engine start skipped (cooldown window)")
      return true
    }
    return try {
      applyRuntimePatches()
      val args = arrayOf(
        nodeBin.absolutePath, "--expose-internals", dshBin.absolutePath, "web", "--port", port.toString(),
      )
      engineProcess = startWithArgs(args, shellEnv())
      // The cooldown is written only after a real start: failure paths don't consume the window (retry is immediate).
      EngineManager.lastStartAttemptAt = now
      LogCollector.log(TAG, "engine started")
      true
    } catch (t: Throwable) {
      Log.e(TAG, "engine start failed", t)
      LogCollector.log(TAG, "engine start FAILED: " + (t.message ?: t.javaClass.simpleName))
      false
    } finally {
      STARTING.set(false)
    }
  }

  /**
   * Spawn the engine, falling back to the system linker when the direct exec
   * is denied: Android 15+ apps targeting SDK 35+ may not exec app-data ELF
   * binaries, but loading them through /system/bin/linker64 is the same
   * mechanism as native libraries (always permitted for app data).
   */
  private fun startWithArgs(args: Array<String>, env: Map<String, String>): Process {
    val log = File(context.filesDir, "engine.log")
    fun build(argv: List<String>): ProcessBuilder =
      ProcessBuilder(argv).also { b ->
        b.environment().putAll(env)
        b.redirectErrorStream(true)
        b.redirectOutput(log)
      }
    return try {
      build(args.toList()).start()
    } catch (e: java.io.IOException) {
      if (e.message?.contains("Permission denied") != true) throw e
      Log.w(TAG, "direct exec denied, falling back to linker64: " + e.message)
      build(listOf("/system/bin/linker64") + args.toList()).start()
    }
  }

  /** Stop the engine process (best-effort). */
  fun stopEngine() {
    engineProcess?.destroy()
    engineProcess = null
    LogCollector.log(TAG, "engine stopped (manual)")
    // Reset the cooldown after a manual stop: returning to the foreground should allow an immediate restart.
    EngineManager.lastStartAttemptAt = 0
  }

  /**
   * Snapshot environment shared by engine/console/log processes (PATH/LD_LIBRARY_PATH/HOME/DSH_HOME/
   * TERMUX_* injected explicitly — the snapshot is self-sufficient, no Termux app needed). Idempotent:
   * safe to call repeatedly (ensurePrivateDshData and the TMPDIR mkdirs are both idempotent).
   */
  fun shellEnv(): Map<String, String> {
    val preload = File(usrDir, "lib/libtermux-exec-ld-preload.so")
    // Cert paths hardcoded at Termux package build time (/data/data/com.termux/...) break after the
    // PREFIX relocation; relocate-snapshot.py doesn't rewrite ELF, so env vars cover the functional
    // paths — curl/wget/git https CA validation depends on them (v0.12.3-FX-2).
    val cert = File(usrDir, "etc/tls/cert.pem").takeIf { it.exists() }
    val certEnv = if (cert != null) {
      mapOf(
        "SSL_CERT_FILE" to cert.absolutePath,
        "CURL_CA_BUNDLE" to cert.absolutePath,
        "GIT_SSL_CAINFO" to cert.absolutePath,
      )
    } else emptyMap()
    return mapOf(
      "PATH" to (usrDir.absolutePath + "/bin:/system/bin"),
      "LD_LIBRARY_PATH" to (usrDir.absolutePath + "/lib"),
      "HOME" to homeDir.absolutePath,
      // DSH_HOME always stays in the private domain (FUSE forbids symlinks, so the public domain
      // can't maintain the profiles/node_modules flat fallback); all runtime user data lives in private
      // files/home/.dsh, and public Documents/dshdata is only the export repo.
      "DSH_HOME" to ensurePrivateDshData().absolutePath,
      // os.tmpdir() falls back to the baked-in Termux tmp on Android
      // (unwritable from the app domain); keep spill inside filesDir.
      "TMPDIR" to File(homeDir, "tmp").apply { mkdirs() }.absolutePath,
      // Android 16 forbids exec of app-data ELF regardless of targetSdk
      // (observed on Android 16/vivo: direct exec EACCES even at targetSdk
      // 34). Termux's execve hook re-routes denied execs through
      // /system/bin/linker64 (same mechanism as JNI libs); the snapshot
      // ships libtermux-exec-*-ld-preload.so. The hook only rewrites for
      // untrusted_app_25/27 SELinux domains, so force mode is required.
      "LD_PRELOAD" to preload.absolutePath,
      "TERMUX_EXEC__SYSTEM_LINKER_EXEC__MODE" to "force",
      "TERMUX_EXEC__EXECVE_CALL__INTERCEPT" to "1",
      "TERMUX__ROOTFS" to usrDir.parentFile.absolutePath,
      "TERMUX__PREFIX" to usrDir.absolutePath,
      "TERMUX_APP__DATA_DIR" to context.filesDir.parentFile.absolutePath,
      "TERMUX_APP__LEGACY_DATA_DIR" to "/data/data/com.dsharnessmobile.shell",
      "TERMUX_VERSION" to BuildConfig.TERMUX_VERSION,
      // Directory-picker endpoint auth token (validated by the web-compat plugin via x-dsh-pick-token).
      "DSH_PICK_TOKEN" to (pickToken ?: ""),
      // Vision backend (Qwen-VL) API key: read from a private file rather than hardcoded in source.
      "DASHSCOPE_API_KEY" to (File(context.filesDir, "dashscope-key.txt").takeIf { it.exists() }?.readText()?.trim() ?: ""),
    ) + certEnv
  }

  companion object {
    private const val TAG = "dsh-engine"

    /** Watchdog/retry backoff: no new start within this window of the last
     *  attempt. Cold node boot on the phone takes 20-45s (plugin tree + first
     *  bind); a 5s watchdog poll would otherwise race a healthy boot and
     *  double-start the engine (device-observed EADDRINUSE). 90s covers the
     *  slowest observed boot with margin. */
    const val START_COOLDOWN_MS = 90_000L

    /** Process-level start CAS: visible across EngineManager instances (double-start race guard). */
    val STARTING = java.util.concurrent.atomic.AtomicBoolean(false)

    /** Last real start time (epoch ms); the watchdog cooldown-window baseline. */
    @Volatile
    var lastStartAttemptAt: Long = 0

    /**
     * Process-level shared directory-picker auth token (C1 fix, 2026-08-16):
     * generated once, then reused by every EngineManager instance in the process — MainActivity
     * rebuilds and EngineService watchdog engine restarts never lose/rotate the token, so auth stays
     * consistent even after the engine-side fail-closed (empty token → reject) path.
     */
    @Volatile
    var sharedPickToken: String? = null

    /** Get (or generate on first call) the process-level pick token. */
    fun ensurePickToken(): String {
      sharedPickToken?.let { return it }
      val token = java.util.UUID.randomUUID().toString()
      sharedPickToken = token
      return token
    }
  }
}
